version: '2'
services:
  redis:
    container_name: backendRedis
    image: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    restart: always
    container_name: backendDB
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: vq012mv9
    volumes:
      - ./data:/var/lib/postgresql/data